### ISSUE TITLE
merge Infobox_Ville to Infobox_Subdivision_administrative

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#14]
@jplu: http://fr.wikipedia.org/wiki/Template:Infobox_Ville redirects to https://fr.wikipedia.org/wiki/Modèle:Infobox_Subdivision_administrative. Therefore the former is never used, any fields mapped in it have no effect, and it's confusing.

Please merge Mapping fr:Infobox Ville into Mapping fr:Infobox_Subdivision_administrative and then delete Mapping fr:Infobox Ville, as explained at #3. I'll be working on a similar task for Geopolitical organization,s ee #4.

PS: I came to this while wondering what is typeCoordinate. I've added a comment to http://mappings.dbpedia.org/index.php/OntologyProperty:TypeCoordinate, please see if it's accurate. This is the sort of documentation we need for _every_ property and class

**Comment by jplu** [comment]
Ok, I checked if all the properties in the mapping of "Ville" was include in the one of "Subdivision Administrative" and as it was the case, I deleted the mapping of Ville to modify it with a redirect link as you can see in following the new link http://mappings.dbpedia.org/index.php?title=Mapping_fr:Infobox_Ville

> please see if it's accurate

Yes it is.

**Comment by VladimirAlexiev** [comment]
I see Jimkont deleting redirect pages, so I did the same. (Maybe the redirects mess something in the extractor framework).

But the wikipedia dump won't ever include Template:Infobox_Ville, so there's no need for the redirect.
