### ISSUE TITLE
Mapping_el:Quote_box is utter nonsense

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#27]
http://mappings.dbpedia.org/index.php/Mapping_el:Quote_box is utter nonsense.
- It's mapped to Road, so eg the Greek article on History (https://el.wikipedia.org/w/index.php?title=Ιστορία&action=edit) will be mapped to Road
- Most of the properties (eg size, style) have no semantic significance.
- I especially like the mapping 1->number ;-)

Should be changed to emit use IntermediateNode and emit something like this (extra props and class added as needed):

```
<Ιστορία>
  quote <Ιστορία__1>.
<Ιστορία__1> a Quote;
  title "...";
  quote "...";
  dct:source <Λουκιανός>, <Πῶς δεῖ ἱστορίαν συγγράφειν>.
```

BUT I would first check WikiQuote to see what requirements or data model they have about quotes. Eg the original source is written as

```
|source =[[Λουκιανός]], [[Πῶς δεῖ ἱστορίαν συγγράφειν]] 7.18.
```

and maybe it's not sufficient to just list the two sources

**Comment by jimregan** [comment]
This looks like something for the ignore list: https://github.com/dbpedia/extraction-framework/pull/331

**Comment by jimkont** [comment]
you're right, I deleted this
