### ISSUE TITLE
what's titleLink?

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#44]
@jplu: please comment in http://mappings.dbpedia.org/index.php/OntologyProperty_talk:LinkTitle

What's this for? It's unused.

The standard extractor extracts a bunch of links for every page as props wikiPageWikiLink. Would your prop be correlated to this, and how would you couple the two? Could you give a Tutle example of what you intend?

If you don't intent to use it, please delete it

**Comment by jplu** [comment]
Hi @VladimirAlexiev 

This property is there to keep the title of a link. For example, let's take this like `[[Arrondissements de Paris|arrondissements]]`, this property will take the value `arrondissements`.

It is not used because for now, I didn't had time to finish to implement this feature in the framework.

**Comment by VladimirAlexiev** [comment]
Could you give a Tutle example of what you intend to produce?

**Comment by jplu** [comment]
I give example and more detail there: https://github.com/dbpedia/extraction-framework/issues/189

But to copy/paste this example, here what I had in mind. Let's take this simple infobox from http://fr.wikipedia.org/wiki/Iron_Man_%28comics%29:

```
{{Infobox Personnage (fiction)
| film                  = [[Iron Man (film)|Iron Man]]
}}
```

To give this result:

```
<http://dbpedia.org/resource/Iron_Man_(comics)> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/FictionalCharacter> .
<http://dbpedia.org/resource/Iron_Man_(comics)> <http://dbpedia.org/ontology/movie> <http://dbpedia.org/resource/Iron_Man_(film)> .
<http://dbpedia.org/resource/Iron_Man_(film)> <http://dbpedia.org/ontology/hasLinkTitle> _:title .
_:title <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/LinkTitle> .
_:title <http://www.w3.org/2000/01/rdf-schema#label> "Iron Man"@fr .
_title <http://dbpedia.org/ontology/linkTitleFrom> <http://dbpedia.org/resource/Iron_Man_(film)> .
```
