### ISSUE TITLE
Domain errors in the mappings (2K+)

### ISSUE THREAD

**Issue by jimkont** [dbpedia/mappings-tracker#57]
As announced on the mailing list, here is a list of domain errors in the mappings wiki.

https://docs.google.com/spreadsheets/d/1FSh5XRVNmztO90sAJ13tLETqTUl7P5EASP_6OG1N-iY/edit#gid=0

**Comment by VladimirAlexiev** [comment]
Very useful! Fixed 2, 1998 to go :-)
What is the underscore in eg "expected domain = Person,_PersonalEvent"?

**Comment by VladimirAlexiev** [comment]
When was this taken? http://mappings.dbpedia.org/index.php/Mapping_bg:Инфо_училище is listed but it was deleted on 6 Feb 2015 (the right one is http://mappings.dbpedia.org/index.php/Mapping_bg:Училище)

**Comment by jimkont** [comment]
Should be the latest mappings (~2 days ago), @chile12 did you create the RDF with the lastest ontology / mappings?
Otherwise I'll create a recent one and re-post

**Comment by jimkont** [comment]
See https://github.com/dbpedia/ontology-tracker/issues/6 for the `,_` issue

**Comment by jimkont** [comment]
An updated evaluation can be found here
https://docs.google.com/spreadsheets/d/10nOQzSoW8l42ogupLqishdmoFco2ZLs42glaW1B0zX8/edit#gid=0

**Comment by Nono314** [comment]
There are 244 entries with expected domain Thing.

Mass setting them to owl:Thing should fix them since everything is an owl:Thing?

**Comment by jimkont** [comment]
These properties had `Thing` as rdfs:domain instead of `owl:Thing` and it was translated as `dbo:Thing`

**Comment by VladimirAlexiev** [comment]
Ok, so "_" comes from a space someone put after the comma.
I've made col "mapping" into a hyperlink to edit the mapping, and made first col "Lang" (very useful for filtering).

**Comment by jimkont** [comment]
From now on this report is available online here with the help of @chile12 
http://mappings.dbpedia.org/validation/index.html

the data will be updated on a daily basis & your feedback is welcome

**Comment by VladimirAlexiev** [comment]
@chile12 that's great! Suggestions for improvement:
- move the filter boxes on top (I almost missed them at the bottom)
- make the Mapping col into Edit link not View link (eg http://mappings.dbpedia.org/index.php?title=Mapping_bg:Геообект&action=edit  instead of http://mappings.dbpedia.org/index.php/Mapping_bg:Геообект)
- make the Predicate, Expected & Existing cols into Edit links (eg http://mappings.dbpedia.org/index.php?title=OntologyProperty:child&action=edit instead of http://dbpedia.org/ontology/child)

Will look at lang="en|bg"

**Comment by VladimirAlexiev** [comment]
- add link "hiearchy" to "Existing", going to the position of  that class in the hierarchy, eg: http://mappings.dbpedia.org/server/ontology/classes/#Monarch

**Comment by VladimirAlexiev** [comment]
Added a brief doc of this wonderful service: http://mappings.dbpedia.org/index.php/Main_Page#Domain_Validation

**Comment by jimkont** [comment]
done, should we leave this issue open?

**Comment by VladimirAlexiev** [comment]
Close it. Fixing all the problems is a lot of ongoing work
