### ISSUE TITLE
it's activeYears not activeYear

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#83]
Uros Milosevic has created 14 mk mappings using [dbo:activeYear](http://mappings.dbpedia.org/index.php/OntologyProperty:ActiveYear)
http://mappings.dbpedia.org/index.php/Special:WhatLinksHere/OntologyProperty:ActiveYear

But in fact the property is [dbo:activeYears](http://mappings.dbpedia.org/index.php/OntologyProperty:ActiveYear). Please fix the mappings and delete the wrong property.

**Comment by jimkont** [comment]
fixed
