### ISSUE TITLE
merge operatedBy to operator

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#84]
Merge [dbo:operatedBy](http://mappings.dbpedia.org/index.php?title=Special:WhatLinksHere/OntologyProperty:OperatedBy&limit=500) to [dbo:operator](http://mappings.dbpedia.org/index.php?title=Special:WhatLinksHere/OntologyProperty:Operator&limit=500), which means the same and has more instances

**Comment by jimkont** [comment]
+1

**Comment by nandana** [comment]
+1
