### ISSUE TITLE
dbo:Website is equivalent with schema:WebSite, not schema:WebPage

### ISSUE THREAD

**Issue by RubenVerborgh** [dbpedia/mappings-tracker#92]
Currently, [`dbo:Website`](http://mappings.dbpedia.org/index.php/OntologyClass:Website) lists `schema:WebPage` as `owl:equivalentClass` instead of the correct `schema:WebSite`.

**Comment by VladimirAlexiev** [comment]
@jimkont @kurzum Waaait a second. Isn't the master of the ontology still the mapping wiki????
Fixed at http://mappings.dbpedia.org/index.php/OntologyClass:Website

**Comment by kurzum** [comment]
@VladimirAlexiev yes, but as you suggested, the discussion happens here. 
@RubenVerborgh if you have an account you can just change it on this page: http://mappings.dbpedia.org/index.php/OntologyClass:Website

**Comment by RubenVerborgh** [comment]
Fixed by @VladimirAlexiev on the wiki.

**Comment by VladimirAlexiev** [comment]
@kurzum My question was not about the discussion but about fixing in ontologies/dbpedia.ttl, which would get overwritten from the wiki. Cheers!
